# Generated by Django 2.2.7 on 2019-11-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0002_auto_20191124_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': ('add',), 'permissions': (('give_refund', 'Can refund customers'), ('can_hire', 'Can hire employees'), ('delete', 'delete the items'))},
        ),
    ]
